adding ovveride option

diff --git a/.github/workflows/pipeline.yaml b/.github/workflows/pipeline.yaml
--- a/.github/workflows/pipeline.yaml
+++ b/.github/workflows/pipeline.yaml
@@ -14,21 +14,38 @@ on:
         description: 'VM name prefix to manage'
         required: true
         default: 'vm-dev'
+      override_start:
+        description: 'Override to force start of VMs'
+        default: 'false'
+      override_shutdown:
+        description: 'Override to force shutdown of VMs'
+        default: 'false'
 
 jobs:
+  validate-overrides:
+    runs-on: ubuntu-latest
+    steps:
+      - name: Check for conflicting overrides
+        run: |
+          if [ "${{ github.event.inputs.override_start }}" == "true" ] && [ "${{ github.event.inputs.override_shutdown }}" == "true" ]; then
+            echo -e "\033[36m Error: Both override_start and override_shutdown cannot be true at the same time. \033[0m"
+            exit 1
+          fi
+
   start-vms:
     runs-on: ubuntu-latest
-    if: github.event_name == 'schedule' && contains(github.event.schedule, '30 6')
+    needs: validate-overrides
+    if: (github.event_name == 'schedule' && contains(github.event.schedule, '30 6')) || (github.event_name == 'workflow_dispatch' && github.event.inputs.override_start == 'true')
     steps:
       - name: Checkout code
-        uses: actions/checkout@v2
+        uses: actions/checkout@v4
 
       - name: Set up Azure CLI
         uses: azure/CLI@v1
 
-      - name: Start VMs with Prefix
+      - name: Start VMs with Prefix ${{ github.event.inputs.vmPrefix }}
         run: |
-          chmod +x ./your-script.sh  # Ensure your script is executable
+          chmod +x .vm-start.sh  # Ensure your script is executable
           ./vm-start.sh ${{ github.event.inputs.vmPrefix }}
         env:
           AZURE_SUBSCRIPTION_ID: ${{ env.AZURE_SUBSCRIPTION_ID }}
@@ -38,7 +55,8 @@ jobs:
 
   stop-vms:
     runs-on: ubuntu-latest
-    if: github.event_name == 'schedule' && contains(github.event.schedule, '00 21')
+    needs: validate-overrides
+    if: (github.event_name == 'schedule' && contains(github.event.schedule, '00 21')) || (github.event_name == 'workflow_dispatch' && github.event.inputs.override_shutdown == 'true')
     steps:
       - name: Checkout code
         uses: actions/checkout@v2
@@ -46,12 +64,12 @@ jobs:
       - name: Set up Azure CLI
         uses: azure/CLI@v1
 
-      - name: Stop VMs with Prefix
+      - name: Stop VMs with Prefix ${{ github.event.inputs.vmPrefix }}
         run: |
-          chmod +x ./shutdown-script.sh  # Ensure your shutdown script is executable
+          chmod +x ./vm-shutdown.sh  # Ensure your shutdown script is executable
           ./vm-shutdown.sh ${{ github.event.inputs.vmPrefix }}
         env:
-          AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
-          AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
+          AZURE_SUBSCRIPTION_ID: ${{ env.AZURE_SUBSCRIPTION_ID }}
+          AZURE_CLIENT_ID: ${{ env.AZURE_CLIENT_ID }}
+          AZURE_TENANT_ID: ${{ env.AZURE_TENANT_ID }}
           AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
-          AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
