tag script and pipeline modification

diff --git a/.github/workflows/pipeline-tag-value.yaml b/.github/workflows/pipeline-tag-value.yaml
--- a/.github/workflows/pipeline-tag-value.yaml
+++ b/.github/workflows/pipeline-tag-value.yaml
@@ -1,11 +1,11 @@
 name: TAG - Manage VM uptime
 
-on: #deactivate cron schedule in example code
-  # # Schedule 1: Start VMs every day at 07:30 AM
+on:
+  # Schedule 1: Start VMs every day at 07:30 AM CEST (UTC+2)
   schedule:
-    - cron: '30 5 * * *'  # 07:30 AM CEST (UTC+2)  (Daylight Saving Time)
-  # # Schedule 2: Stop VMs every day at 10:00 PM Norwegian time (CET/CEST)
-    - cron: '00 22 * * *'  # 23:00 PM CEST (UTC+2)  (Daylight Saving Time)
+    - cron: '30 5 * * *'  # 05:30 AM UTC
+  # Schedule 2: Stop VMs every day at 10:00 PM CEST (UTC+2)
+    - cron: '00 20 * * *'  # 08:00 PM UTC
 
   # Manual trigger for both start and stop jobs
   workflow_dispatch:
@@ -15,23 +15,23 @@ on: #deactivate cron schedule in example code
         required: true
         default: 'vm-automation-start-stop'
       vmTagValue:
-        description: 'Tag Value to query in theh script'
+        description: 'Tag Value to query in the script'
         required: true
         default: 'true'
       override_start:
-        description: Manual run, start VMs? (false/true)'
+        description: 'Manual run, start VMs? (false/true)'
         default: 'false'
         type: choice
         options:
           - 'true'
           - 'false'
       override_shutdown:
-          description: 'Manual run, shutdown VMs? (false/true)'
-          default: 'false'
-          type: choice
-          options:
-            - 'true'
-            - 'false'
+        description: 'Manual run, shutdown VMs? (false/true)'
+        default: 'false'
+        type: choice
+        options:
+          - 'true'
+          - 'false'
 
 env:
   AZURE_CLIENT_ID: ${{ vars.CLIENT_ID }}
@@ -45,14 +45,14 @@ jobs:
       - name: Check for conflicting overrides
         run: |
           if [ "${{ github.event.inputs.override_start }}" == "true" ] && [ "${{ github.event.inputs.override_shutdown }}" == "true" ]; then
-            echo -e "\033[36m Error: Both override_start and override_shutdown cannot be true at the same time. \033[0m"
+            echo "Error: Both override_start and override_shutdown cannot be true at the same time."
             exit 1
           fi
 
   start-vms:
     runs-on: ubuntu-latest
     needs: validate-overrides
-    if: (github.event_name == 'schedule' && contains(github.event.schedule, '30 5')) || (github.event_name == 'workflow_dispatch' && github.event.inputs.override_start == 'true')
+    if: (github.event_name == 'schedule') || (github.event_name == 'workflow_dispatch' && github.event.inputs.override_start == 'true')
     steps:
       - name: Checkout code
         uses: actions/checkout@v4
@@ -60,15 +60,15 @@ jobs:
       - name: az login
         run: az login --service-principal -u $AZURE_CLIENT_ID -p $AZURE_CLIENT_SECRET --tenant $AZURE_TENANT_ID
 
-      - name: Start VMs that contain Tag '${{ github.event.inputs.vmTag }}' with value '${{ github.event.inputs.vmTagValue }}'
+      - name: Start VMs with Tag '${{ github.event.inputs.vmTag }}' and value '${{ github.event.inputs.vmTagValue }}'
         run: |
-          chmod +x ./vm-start.sh  # Ensure your script is executable
-          ./vm-start.sh ${{ github.event.inputs.vmTagValue }} ${{ github.event.inputs.vmTag }}
+          chmod +x ./vmTag-start.sh
+          ./vmTag-start.sh ${{ github.event.inputs.vmTag }} ${{ github.event.inputs.vmTagValue }}
 
   stop-vms:
     runs-on: ubuntu-latest
     needs: validate-overrides
-    if: (github.event_name == 'schedule' && contains(github.event.schedule, '00 22')) || (github.event_name == 'workflow_dispatch' && github.event.inputs.override_shutdown == 'true')
+    if: (github.event_name == 'schedule') || (github.event_name == 'workflow_dispatch' && github.event.inputs.override_shutdown == 'true')
     steps:
       - name: Checkout code
         uses: actions/checkout@v4
@@ -76,7 +76,7 @@ jobs:
       - name: az login
         run: az login --service-principal -u $AZURE_CLIENT_ID -p $AZURE_CLIENT_SECRET --tenant $AZURE_TENANT_ID
 
-      - name: Stop VMs that contain Tag '${{ github.event.inputs.vmTag }}' with value '${{ github.event.inputs.vmTagValue }}'
+      - name: Stop VMs with Tag '${{ github.event.inputs.vmTag }}' and value '${{ github.event.inputs.vmTagValue }}'
         run: |
-          chmod +x ./vm-shutdown.sh  # Ensure your shutdown script is executable
-          ./vm-shutdown.sh ${{ github.event.inputs.vmTagValue }} ${{ github.event.inputs.vmTag }}
+          chmod +x ./vmTag-shutdown.sh
+          ./vmTag-shutdown.sh ${{ github.event.inputs.vmTag }} ${{ github.event.inputs.vmTagValue }}
